# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: pytest-metrics-xcomet

on:
  # Trigger the workflow on push to main or any pull request
  push:
    branches: ["main", "develop"]
  pull_request:
    types: ["opened", "synchronize"]

jobs:
  build:

    strategy:
      matrix:
        platform: ["ubuntu-latest", "windows-latest"]
        python-version: ["3.10", "3.11"]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Test with pytest
      run: |
        poetry run huggingface-cli login --token ${{ secrets.HUGGINGFACE_TOKEN }}
        poetry run pytest -m "metrics_xcomet"
